# Generated by Django 5.1.1 on 2024-09-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toy',
            options={'ordering': ['name']},
        ),
    ]
